### ISSUE TITLE
Unhandled 'error' event after npm run start.

### ISSUE THREAD

**Issue by davidfufu** [react-materialize/webpack-boilplate#5]
Cloned, installed, and ran npm start.

```
 test-material@1.0.0 start /home/askeladde/Documents/0-Root/1-Programming/Javascript/Web_Development/React/Currently_Working_On/TESTING-MATERIALIZE-REACT MATERIALIZE COMPONENTS BOILERPLATE/webpack-boilplate
webpack-dev-server --config webpack.config.js --progress --colors

 70% 1/1 build modulesevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-material@1.0.0 start: `webpack-dev-server --config webpack.config.js --progress --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-material@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/askeladde/.npm/_logs/2017-08-22T17_26_39_173Z-debug.log
 …/webpack-boilplate  master ?  3.6.1                                 1 ↵ 
```

NPM version 5.3
Node version 6.11.2

**Comment by Yunnkii** [comment]
请问解决了吗

**Comment by joaofolle** [comment]
Same error here...

**Comment by alextrastero** [comment]
This happens when you already have an npm server running on that PORT
